name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'converter/odata'
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1

    - name: Create Build Directory
      run: mkdir _build

    - name: Current directory
      run: pwd

    - name: Create Build Directory
      run: cd converter/odata

    - name: Restore Packages
      run: nuget restore OdataSwaggerConverter.sln

    - name: Build Solution
      run: |
        msbuild.exe OdataSwaggerConverter.sln -property:Configuration=Release