name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'converter/odata3'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 4.5
    - name: Restore dependencies
      working-directory: ${{env.workingDirectory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.workingDirectory}}
      run: dotnet build --no-restore
    - name: Test
      working-directory: ${{env.workingDirectory}}
      run: dotnet test --no-build --verbosity normal
