name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'converter/odata'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'
    - name: List SDKs
      run: dotnet --list-sdks
    - name: Restore dependencies
      working-directory: ${{env.workingDirectory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.workingDirectory}}
      run: dotnet build --no-restore -f net45
    - name: Test
      working-directory: ${{env.workingDirectory}}
      run: dotnet test --no-build --verbosity normal
