name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'converter/odata'
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      shell: cmd
      run: call .\Build.cmd
    - name: List SDKs
      run: dotnet --list-sdks
    - name: Restore dependencies
      working-directory: ${{env.workingDirectory}}
      run: dotnet restore
    - name: Test
      working-directory: ${{env.workingDirectory}}
      run: dotnet test --no-build --verbosity normal
