name: OData Converter tests

on:
  push:
  pull_request:

jobs:
  build:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env:
      workingDirectory: 'converter'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Restore dependencies
      working-directory: ${{env.workingDirectory}}
      run: dotnet restore
    - name: Build
      working-directory: ${{env.workingDirectory}}
      run: dotnet build --no-restore
    - name: Test
      working-directory: ${{env.workingDirectory}}
      run: dotnet test --no-build --verbosity normal
